import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";
import AuthProvider from './context/AuthProvider'



const poppin = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Forex Fusion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppin.className} bg-primary relative` }>
        <AuthProvider>
        <Navbar />
        {children}
        <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
